class Commands:

    COMMANDS_PERMISSIONS = {
        'create_user': ('create', 'user'),
        'get_users': ('read', 'user'),
        'get_user': ('read', 'user'),
        'update_user': ('update', 'user'),
        'delete_user': ('delete', 'user'),
        'create_department': ('create', 'department'),
        'get_departments': ('read', 'department'),
        'get_department': ('read', 'department'),
        'update_department': ('update', 'department'),
        'delete_department': ('delete', 'department'),
        'create_event': ('create', 'event'),
        'get_events': ('read', 'event'),
        'get_incomplete_events': ('filter_events', 'event'),
        'filter_own_events': ('filter_own_events', 'event'),
        'get_event': ('read', 'event'),
        'update_event': ('update', 'event'),
        'assign_support_contact': ('assign_support_contact', 'event'),
        'delete_event': ('delete', 'event'),
        'create_client': ('create', 'client'),
        'get_clients': ('read', 'client'),
        'get_client': ('read', 'client'),
        'update_client': ('update', 'client'),
        'delete_client': ('delete', 'client'),
        'create_contract': ('create', 'contract'),
        'get_contracts': ('read', 'contract'),
        'filter_contracts': ('filter_contracts', 'contract'),
        'get_contract': ('read', 'contract'),
        'update_contract': ('update', 'contract'),
        'delete_contract': ('delete', 'contract'),
    }
